version: 0.2

env:
  variables:
    NLW_URL: "$ENV_NLW_URL"
  secrets-manager: # as an example from CodeBuild, private token in environment from Secrets Manager
    NLW_TOKEN: ENV_NLW_TOKEN

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - pwd
      - ls -latr
      - whoami

  build:
    commands:
      - ls -latr /home/neoload

      # - |
      # /home/neoload/neoload/bin/NeoLoadCmd \
      #     -project /var/lib/jenkins/workspace/load/CPVWeatherCrisis.nlp \
      #     -project /var/lib/jenkins/workspace/load/neoload/test/cpv-apm/scenario.yaml \
      #     -launch 'Post Nominal Test' -testResultName 'Load Test (build 8)' \
      #     -description 'WeatherCrisis Nominal Test' \
      #     -report /var/lib/jenkins/workspace/load/neoload-report/report.html,/var/lib/jenkins/workspace/load/neoload-report/report.xml \
      #     -SLAJUnitResults /var/lib/jenkins/workspace/load/neoload-report/junit-sla-results.xml \
      #     -noGUI \
      #     -nlweb \
      #     -L 'API=/var/lib/jenkins/workspace/load/neoload/lg/docker-lg.txt' \
      #     -L 'Dynatrace=/var/lib/jenkins/workspace/load/neoload/lg/local-lg.txt' \
      #     -nlwebToken [...] \
      #     -NTS https://neoload-rest.saas.neotys.com:443/nts \
      #     -NTSLogin 'user:encpass' \
      #     -leaseLicense '[...]:51:1'

  post_build:
    commands:
      # produce junit report on SLAs
      - pwd
      - ls -latr
      # if a prior step failed or err'd, don't bother waiting
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"

#reports:
  # report-name-or-arn:
  #   files:
  #     - $CODEBUILD_SRC_DIR/neoload_slas.junit.xml
  #   discard-paths: yes
  #   file-format: JunitXml
