trigger: none

pool:
  vmImage: 'windows-latest'
  #'ubuntu-16.04'

variables:
  nlw_url: $(secret_nlw_url)
  nlw_token: $(secret_nlw_token)
  zone_code: wNBKe
  PYTHONUNBUFFERED: 1

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install and Configure NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --version
        neoload login --url $(nlw_url) --workspace Demo $(nlw_token) \
                test-settings --zone $(zone_code) --lgs 1 --scenario sanityScenario createorpatch "Azure Sample"
                project --path $(Build.SourcesDirectory)/example_test/ upload cur

  - task: Bash@3
    displayName: Run NeoLoad Test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload run \
                       --web-vu 25 \
                       --detached \
                       --as-code default.yaml,slas/uat.yaml \
                       --name "Azure_sidecars_$(Build.BuildNumber)" \
                       --description "Azure example load test with sidecars; $(Build.BuildUri)" \
                       cur
  - task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       whoami
       ls -latr $(Common.TestResultsDirectory)

       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla

       ls -latr $(Common.TestResultsDirectory)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
