trigger: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: 9h2lZ
  PYTHONUNBUFFERED: 1

# create sidecar containers, attach them to a zone; provide supply this pipeline demands
resources:
  containers:
  - container: neoload_ctrl
    image: neotys/neoload-controller:latest
    env: { MODE: Managed, NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code) }
  - container: lg1
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code), LG_HOST=lg1, LG_PORT=7101, AGENT_SERVER_PORT=7101 }
  - container: lg2
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code), LG_HOST=lg2, LG_PORT=7102, AGENT_SERVER_PORT=7102 }

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test
  services:
    neoload_ctrl: neoload_ctrl
    lg1: lg1
    lg2: lg2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --profile docker --token $(nlw_token) --zone $(zone_code)

  - task: Bash@3
    displayName: Run NeoLoad Test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        cd $(Build.SourcesDirectory)

        neoload --scenario sanityScenario \
                -f example_test/default.yaml \
                -f example_test/slas/uat.yaml \
                --testname "Azure_sidecars_$(Build.BuildNumber)" \
                --testdesc "Azure example load test with sidecars; $(Build.BuildUri)" \
                --attach zone#2 \
                --junitsla $(Common.TestResultsDirectory)/neoload-slas.xml

  - task: Bash@3
    displayName: Report Controller Logs
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        NL_USER_DIR=/home/neoload/.neotys/neoload
        CTRL_ID=$(docker ps --filter "name=neoload_ctrl" --format "{{.ID}}")
        docker exec -t $CTRL_ID ls -latr $NL_USER_DIR
        NL_VERSION=$(docker exec -t $CTRL_ID find $NL_USER_DIR -maxdepth 1 -type d -name 'v*.*' -exec basename {} ';')
        NL_VERSION=$(echo $NL_VERSION | tr -d '\n' | tr -d '\r')
        echo $NL_VERSION
        docker exec -t $CTRL_ID ls -latr $NL_USER_DIR/$NL_VERSION/logs/
        docker cp $CTRL_ID:$NL_USER_DIR/$NL_VERSION/logs/ $(Common.TestResultsDirectory)
        cat $(Common.TestResultsDirectory)/logs/neoload.log

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
