trigger: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: 9h2lZ
  PYTHONUNBUFFERED: 1

# create sidecar containers, attach them to a zone; provide supply this pipeline demands
resources:
  containers:
  - container: neoload_ctrl
    image: neotys/neoload-controller:latest
    env: { MODE: Managed, NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code) }
  - container: lg1
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code), LG_HOST=lg1, LG_PORT=7101, AGENT_SERVER_PORT=7101 }
  - container: lg2
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code), LG_HOST=lg2, LG_PORT=7102, AGENT_SERVER_PORT=7102 }

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test
  services:
    neoload_ctrl: neoload_ctrl
    lg1: lg1
    lg2: lg2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --version

  - task: Bash@3
    displayName: Run NeoLoad Test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        cd $(Build.SourcesDirectory)

        mkdir neoload_project && unzip example_test/openstreetmaps_nlp.zip -d neoload_project
        cp slas/uat.yaml neoload_project/uat.yaml

        neoload login $(nlw_token) \
                test-settings --zone $(zone_code) --lgs 2 --scenario sanityScenario patch "Azure_sidecars" \
                project --path neoload_project/ upload "Azure_sidecars"
        
        neoload run \
                       --web-vu 50 \
                       --as-code uat.yaml \
                       --name "TestLaunchedFromAzureCI_build_$(Build.BuildNumber)" \
                       --description "Azure example with meta; $(Build.BuildUri)" \
                       "Azure_sidecars"
  - task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla

  - task: Bash@3
    displayName: Report Controller Logs
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        CTRL_ID=$(docker ps --filter "name=neoload_ctrl" --format "{{.ID}}")
        echo $CTRL_ID
        NL_USER_DIR=/home/neoload/.neotys/neoload
        NL_VERSION=$(docker exec -t $CTRL_ID find $NL_USER_DIR -maxdepth 1 -type d -name 'v*.*' -exec basename {} ';' | tr -d '\n' | tr -d '\r')
        echo $NL_VERSION
        docker cp $CTRL_ID:$NL_USER_DIR/$NL_VERSION/logs/ $(Common.TestResultsDirectory)
        ls -latr $(Common.TestResultsDirectory)
        cat $(Common.TestResultsDirectory)/logs/neoload.log

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
