version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
  pre_build:
    commands:
      # get samples and specific branch of CLI for sla fastfail functionality
      - git clone https://github.com/Neotys-Labs/neoload-cli.git
      - cd neoload-cli && git checkout topic-fastfail-command && git pull
      # process diags
      - pwd
      - ls -latr
      # install the NeoLoad CLI Python client
      - python3 -m pip install .
      #- pip install neoload
  build:
    commands:
      # create a profile and connect to the platform
      - neoload login --url ${NLW_URL} ${NLW_TOKEN}
      # configure the test
      - neoload test-settings --zone ${NLW_DYNAMIC_ZONE} --scenario fullTest createoruse "example-AWScodebuild-SLAfail" \
                project --path tests/neoload_projects/example_1/ upload
      # run the test
      - neoload run --detached --web-vu 25 --as-code default.yaml,slas/uat.yaml
      # wait for early failure signals, stop test if any SLA over 30% failed
      - neoload fastfail --max-failure 30 slas cur
  post_build:
    commands:
      # wait for test finalization
      - neoload wait cur
